### ISSUE TITLE
ImportError: cannot import name 'import_path' from '_pytest.doctest'

### ISSUE THREAD

**Issue by boolmriver** [git-cloner/llama2-lora-fine-tuning#14]
这个问题怎么解决，pytest是最新的。
Traceback (most recent call last):
  File "/data/home/scv9515/A_suke_file/ALLMs/llama2-lora-fine-tuning/finetune-lora.py", line 45, in <module>
    from transformers.testing_utils import CaptureLogger
  File "/data/home/scv9515/miniconda3/envs/bili/lib/python3.10/site-packages/transformers/testing_utils.py", line 131, in <module>
    from _pytest.doctest import (
ImportError: cannot import name 'import_path' from '_pytest.doctest' (/data/home/scv9515/miniconda3/envs/bili/lib/python3.10/site-packages/_pytest/doctest.py)

**Comment by ListenPOLY** [comment]
我也遇到了，pytest版本8.2.0，
    from _pytest.doctest import (
E   ImportError: cannot import name 'import_path' from '_pytest.doctest' (/home/li/.conda/envs/mindspore_py39/lib/python3.9/site-packages/_pytest/doctest.py)
